unit AnoSeguiPorProgAcaoRel;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRPDFFilter, DB, ADODB, QRCtrls,
  QuickRpt, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPorProgAcaoRel=class(TForm)
    report: TQuickRep;
    QRBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRImage1: TQRImage;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel8: TQRLabel;
    QRSysData1: TQRSysData;
    QRGroup1: TQRGroup;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    qry: TADOQuery;
    DataSource2: TDataSource;
    QRPDFFilter1: TQRPDFFilter;
    QRBand2: TQRBand;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    qryprograma: TStringField;
    qrydescricao: TStringField;
    qryacao: TStringField;
    qrydescricao_1: TStringField;
    qryValor: TBCDField;
    qrySum: TADOQuery;
    qrySumValorPrograma: TBCDField;
    QRDBText3: TQRDBText;
    QRShape3: TQRShape;
    QRShape1: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRShape2: TQRShape;
    procedure QRBand2BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure QRGroup1BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);

  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPorProgAcaoRel: TFrmAnoSeguiPorProgAcaoRel;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

uses data;

{$R *.DFM}

procedure TFrmAnoSeguiPorProgAcaoRel.QRBand2BeforePrint(
  Sender: TQRCustomBand; var PrintBand: Boolean);
begin
   if qry.FieldByName('Valor').Value = 0 then QRLabel10.Enabled := true else QRLabel10.Enabled := false; 
end;

procedure TFrmAnoSeguiPorProgAcaoRel.QRGroup1BeforePrint(
  Sender: TQRCustomBand; var PrintBand: Boolean);
begin
   if qrySum.FieldByName('ValorPrograma').Value = 0 then QRLabel9.Enabled := true else QRLabel9.Enabled := false;
end;

end.
