unit AnoSeguiPoUniFontLimSolRel;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRPDFFilter, DB, ADODB, QuickRpt,
  QRCtrls, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPoUniFontLimSolRel=class(TForm)
    qrySumSolicitado: TADOQuery;
    qySomaLim_: TADOQuery;
    qySomaLim_total: TBCDField;
    qrySumSolicitadovalor: TBCDField;
    report: TQuickRep;
    PageHeaderBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel7: TQRLabel;
    QRSysData1: TQRSysData;
    QRShape2: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel6: TQRLabel;
    QRImage1: TQRImage;
    QRLabel4: TQRLabel;
    qry: TADOQuery;
    DataSource2: TDataSource;
    QRPDFFilter1: TQRPDFFilter;
    QRLabel9: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    qryLimite: TADOQuery;
    qryLimitevalor: TBCDField;
    QRGroup1: TQRGroup;
    qryCont: TADOQuery;
    qryContunorc: TStringField;
    qryContfonte: TStringField;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRLabel2: TQRLabel;
    qryTotalGeral: TADOQuery;
    QRBand1: TQRBand;
    QRLabel16: TQRLabel;
    QRDBText1: TQRDBText;
    qryunorc: TStringField;
    qrydescricao: TStringField;
    qryfonte: TStringField;
    qryValor: TBCDField;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRDBText12: TQRDBText;
    qryTotalLimite: TADOQuery;
    qryTotalLimiteTotalLimite: TBCDField;
    qryTotalGeralTatalSolicitado: TBCDField;
    QRLabel22: TQRLabel;
    QRSysData2: TQRSysData;
    QRBand2: TQRBand;
    QRLabel25: TQRLabel;
    QRDBText3: TQRDBText;
    QRLabel5: TQRLabel;
    QRDBText5: TQRDBText;
    QRLabel21: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel23: TQRLabel;
    QRBand3: TQRBand;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRLabel15: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel8: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel19: TQRLabel;
    procedure QRBand2BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure QRBand3BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPoUniFontLimSolRel: TFrmAnoSeguiPoUniFontLimSolRel;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAnoSeguiPoUniFontLimSolRel.QRBand2BeforePrint(
  Sender: TQRCustomBand; var PrintBand: Boolean);
begin
    if qySomaLim_.FieldByName('total').Value = 0 then QRLabel5.Enabled := true else QRLabel5.Enabled := false;
    if qrySumSolicitado.FieldByName('valor').Value = 0 then QRLabel21.Enabled := true else QRLabel21.Enabled := False;
    QRLabel24.Caption := (FormatCurr('###,###,###',(qySomaLim_.fieldByName('total').Value - qrySumSolicitado.fieldByName('valor').Value)));
    if (qySomaLim_.fieldByName('total').AsFloat - qrySumSolicitado.fieldByName('valor').AsFloat) = 0 then QRLabel23.Enabled := true else QRLabel23.Enabled := false;
end;

procedure TFrmAnoSeguiPoUniFontLimSolRel.QRBand3BeforePrint(
  Sender: TQRCustomBand; var PrintBand: Boolean);
begin
    if qry.FieldByName('valor').Value = 0 then QRLabel15.Enabled := true else QRLabel15.Enabled := false;
    if qryLimite.FieldByName('valor').Value = 0 then QRLabel8.Enabled := true else QRLabel8.Enabled := False;
    QRLabel20.Caption := (FormatCurr('###,###,###',(qry.fieldByName('valor').Value - qryLimite.fieldByName('valor').Value)));
    if  (qry.fieldByName('valor').asFloat - qryLimite.fieldByName('valor').asFloat) = 0 then QRLabel19.Enabled := true else QRLabel19.Enabled := false;

end;

end.
