unit AnoSeguiPorAcaoFontRel;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRPDFFilter, DB, ADODB, QRCtrls,
  QuickRpt, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPorAcaoFontRel=class(TForm)
    report: TQuickRep;
    QRBand1: TQRBand;
    QRLabel1: TQRLabel;
    QRLabel3: TQRLabel;
    QRImage1: TQRImage;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel8: TQRLabel;
    QRSysData1: TQRSysData;
    QRShape1: TQRShape;
    QRGroup1: TQRGroup;
    QRDBText3: TQRDBText;
    qry: TADOQuery;
    DataSource2: TDataSource;
    QRPDFFilter1: TQRPDFFilter;
    qryacao: TStringField;
    qrydescricao: TStringField;
    qryFonte: TStringField;
    qryValor: TBCDField;
    QRDBText4: TQRDBText;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel2: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRBand3: TQRBand;
    QRShape2: TQRShape;
    QRDBText12: TQRDBText;
    QRLabel9: TQRLabel;
    qrySumTotalUnorc: TADOQuery;
    BCDField1: TBCDField;
    QRLabel10: TQRLabel;
    procedure QRGroup1BeforePrint(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPorAcaoFontRel: TFrmAnoSeguiPorAcaoFontRel;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAnoSeguiPorAcaoFontRel.QRGroup1BeforePrint(Sender : TObject);
begin
 if qry.FieldByName('valor').Value = 0 then QRLabel10.Enabled := true else QRLabel10.Enabled := false; 

end;

end.
