unit AnoSeguintePorUnorcProg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, QRPDFFilter, ADODB, QRCtrls,
  QuickRpt, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPoUniProgRel=class(TForm)
    qryUnorc: TADOQuery;
    QRPDFFilter1: TQRPDFFilter;
    report: TQuickRep;
    DataSource1: TDataSource;
    qryUnorcunorc: TStringField;
    qryUnorcUnorcD: TStringField;
    qryUnorcprograma: TStringField;
    qryUnorcprogramaD: TStringField;
    qryUnorcValor: TBCDField;
    qryPrograma: TADOQuery;
    QRDBText5: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    DataSource2: TDataSource;
    qryProgramaprograma: TStringField;
    qryProgramaprogramaD: TStringField;
    qryProgramaacao: TStringField;
    qryProgramaacaoD: TStringField;
    qryProgramaValor: TBCDField;
    qrySumUnorc: TADOQuery;
    qrySumProg: TADOQuery;
    qrySumProgValorPrograma: TBCDField;
    qrySumUnorcValorUnorc: TBCDField;
    PageHeaderBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel7: TQRLabel;
    QRSysData1: TQRSysData;
    QRShape2: TQRShape;
    QRLabel4: TQRLabel;
    QRLabel6: TQRLabel;
    QRImage1: TQRImage;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText9: TQRDBText;
    QRLabel11: TQRLabel;
    QRLabel1: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRShape1: TQRShape;
    QRSysData2: TQRSysData;
    procedure FormCreate(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPoUniProgRel: TFrmAnoSeguiPoUniProgRel;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAnoSeguiPoUniProgRel.FormCreate(Sender : TObject);
begin
(*
005DA2AC   53                     push    ebx
005DA2AD   8BD8                   mov     ebx, eax

* Reference to control TFrmAnoSeguiPoUniProgRel.qryUnorc : TADOQuery
|
005DA2AF   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: DB.Proc_004C6A64
|
005DA2B5   E8AAC7EEFF             call    004C6A64

* Reference to control TFrmAnoSeguiPoUniProgRel.qryPrograma : TADOQuery
|
005DA2BA   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: DB.Proc_004C6A64
|
005DA2C0   E89FC7EEFF             call    004C6A64

* Reference to control TFrmAnoSeguiPoUniProgRel.qrySumUnorc : TADOQuery
|
005DA2C5   8B833C030000           mov     eax, [ebx+$033C]

* Reference to: DB.Proc_004C6A64
|
005DA2CB   E894C7EEFF             call    004C6A64

* Reference to control TFrmAnoSeguiPoUniProgRel.qrySumProg : TADOQuery
|
005DA2D0   8B8340030000           mov     eax, [ebx+$0340]

* Reference to: DB.Proc_004C6A64
|
005DA2D6   E889C7EEFF             call    004C6A64
005DA2DB   5B                     pop     ebx
005DA2DC   C3                     ret

*)
end;



end.