unit AnoSeguiPorAcaoRel;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, QRPDFFilter, ADODB, QRCtrls,
  QuickRpt, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPorAcaoRel=class(TForm)
    report: TQuickRep;
    QRBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRImage1: TQRImage;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRSysData1: TQRSysData;
    QRShape1: TQRShape;
    QRGroup1: TQRGroup;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    qry: TADOQuery;
    QRPDFFilter1: TQRPDFFilter;
    DataSource2: TDataSource;
    qryacao: TStringField;
    qrydescricao: TStringField;
    qryValor: TBCDField;
    QRLabel1: TQRLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPorAcaoRel: TFrmAnoSeguiPorAcaoRel;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

end.
