unit RelAnoSeguinteUnorc;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, QRPDFFilter, ADODB, QRCtrls,
  QuickRpt, jpeg, ExtCtrls;
type
  TFrmAnoSeguiPoUni=class(TForm)
    qryUnorc: TADOQuery;
    QRPDFFilter1: TQRPDFFilter;
    report: TQuickRep;
    DataSource1: TDataSource;
    qryUnorcunorc: TStringField;
    qryUnorcUnorcD: TStringField;
    qryUnorcValor: TBCDField;
    qrySumUnorc: TADOQuery;
    qrySumUnorcValorUnorc: TBCDField;
    PageHeaderBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel7: TQRLabel;
    QRSysData1: TQRSysData;
    QRShape2: TQRShape;
    QRLabel4: TQRLabel;
    QRLabel6: TQRLabel;
    QRImage1: TQRImage;
    QRLabel1: TQRLabel;
    QRBand1: TQRBand;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRLabel2: TQRLabel;
    QRSysData2: TQRSysData;
    QRBand2: TQRBand;
    QRExpr2: TQRExpr;
    QRLabel8: TQRLabel;
    QRShape1: TQRShape;
    procedure FormCreate(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAnoSeguiPoUni: TFrmAnoSeguiPoUni;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAnoSeguiPoUni.FormCreate(Sender : TObject);
begin
      qryUnorc.Open;
end;


end.