unit RelGerencialRec;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRPDFFilter, DB, ADODB, QRCtrls,
  QuickRpt, ExtCtrls;
type
  TFrmRelGerencialRec=class(TForm)
    report: TQuickRep;
    qryEsfera: TADOQuery;
    sQryEsfera: TDataSource;
    QRGroup1: TQRGroup;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRGroup2: TQRGroup;
    QRDBText20: TQRDBText;
    QRLabel13: TQRLabel;
    QRDBText23: TQRDBText;
    QRDBText25: TQRDBText;
    QRDBText10: TQRDBText;
    ColumnHeaderBand1: TQRBand;
    lblEsfera: TQRLabel;
    QRShape11: TQRShape;
    QRLabel4: TQRLabel;
    QRShape21: TQRShape;
    QRLabel61: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel51: TQRLabel;
    QRBand1: TQRBand;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRLabel8: TQRLabel;
    qrySoma: TADOQuery;
    QRDBText3: TQRDBText;
    QRPDFFilter1: TQRPDFFilter;
    QRDBText24: TQRDBText;
    QRDBText4: TQRDBText;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    qryEsferaunorc: TStringField;
    qryEsferaunorcD: TStringField;
    qryEsferaelReceita: TStringField;
    qryEsferareceitaD: TStringField;
    qryEsferaindUso: TStringField;
    qryEsferafonte: TStringField;
    qryEsferaesfera: TStringField;
    qryEsferaCOLUMN1: TBCDField;
    qrySomaCOLUMN1: TBCDField;

  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmRelGerencialRec: TFrmRelGerencialRec;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}




end.