unit SelRelUnorcProg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, ADODB, DBCtrls, CheckLst,
  Buttons, ExtCtrls;
type
  TFrmSelRelUnorcProg=class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    BitBtn1: TBitBtn;
    DBNavigator1: TDBNavigator;
    QRYUnorc: TADOQuery;
    dsUnorc: TDataSource;
    BitBtn2: TBitBtn;
    BitBtn3: TBitBtn;
    lista_chk: TCheckListBox;
    QRYUnorccodigo: TStringField;
    QRYUnorcdescricao: TStringField;
    procedure BitBtn1Click(Sender : TObject);
    procedure FormKeyPress(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure lista_chkClickCheck(Sender : TObject);
    procedure BitBtn2Click(Sender : TObject);
    procedure BitBtn4Click(Sender : TObject);
    procedure BitBtn3Click(Sender : TObject);
    procedure qyrPro(Sender : TObject);
    procedure _PROC_005DD1C1(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
    Lista_SQL : String;
    Procedure ListaOrgaos();
    Procedure Pesquisa(Parametro: String);
  end ;

var
  FrmSelRelUnorcProg: TFrmSelRelUnorcProg;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

uses AnoSeguintePorUnorcProg;

{$R *.DFM}

procedure TFrmSelRelUnorcProg.BitBtn1Click(Sender : TObject);
var lu : String;
    i,chk : integer;
begin

   chk := 0;
   lu :=  ' SELECT distinct a.unorc,u.descricao as UnorcD,a.programa,p.descricao as programaD         '+
          '  ,valor = case  when sum(a.valor)=0 or sum(a.valor)  is null then 0 else sum(a.valor) end '+
          '  FROM ANOSEGUINTE a                                                                       '+
          '  LEFT JOIN UNORC u on u.codigo = a.unorc                                                  '+
          '  LEFT JOIN PROGRAMA p on p.codigo = a.programa                                            '+
          '       LEFT JOIN ACAO ac on ac.codigo = a.acao                                             '+
          '       where 1 = 1                                                                         ';
    FrmAnoSeguiPoUniProgRel := nil;
   if FrmAnoSeguiPoUniProgRel = nil then FrmAnoSeguiPoUniProgRel := TFrmAnoSeguiPoUniProgRel.Create(self);
   with  FrmAnoSeguiPoUniProgRel.qryUnorc, FrmAnoSeguiPoUniProgRel.qryUnorc.SQL do
   begin
       close;
       clear;
       Add(lu);
       For i := 0 to lista_chk.Count -1 do
       Begin

           If lista_chk.Checked[i] Then
           Begin
               chk :=chk +1;
               if chk = 1 then add('and a.unorc = '''+(Copy(lista_chk.Items.Strings[i],1,5))+'''')
               else add('or a.unorc = '''+(Copy(lista_chk.Items.Strings[i],1,5))+'''');

           end;
       end;
       add(' group by a.unorc,u.descricao,a.programa,p.descricao ');
       add(' order by a.unorc,a.programa  ');
       ExecSQL;
       Open;
       First;
    end;
    if FrmAnoSeguiPoUniProgRel.qryUnorc.RecordCount <> 0 then
    begin
        FrmAnoSeguiPoUniProgRel.report.Preview;
        FrmAnoSeguiPoUniProgRel.report.Free;
    end else
    begin
        ShowMessage('N„o ha informaÁ„o para o(s) Org„o(os) selecionado(s)!');
        exit;
    end;

end;

procedure TFrmSelRelUnorcProg.FormKeyPress(Sender : TObject);
begin
(*
005DD410   80391B                 cmp     byte ptr [ecx], $1B
005DD413   7505                   jnz     005DD41A

* Reference to : TApplication._PROC_004676D0()
|
005DD415   E8B6A2E8FF             call    004676D0
005DD41A   C3                     ret

*)
end;

procedure TFrmSelRelUnorcProg.FormCreate(Sender : TObject);
begin
   If dsUnorc.State in [dsinactive] then QRYUnorc.Open;
   Lista_SQL := QRYUnorc.SQL.Text;
   ListaOrgaos;
end;

procedure TFrmSelRelUnorcProg.lista_chkClickCheck(Sender : TObject);
begin
(*
005DD568   55                     push    ebp
005DD569   8BEC                   mov     ebp, esp
005DD56B   6A00                   push    $00
005DD56D   53                     push    ebx
005DD56E   56                     push    esi
005DD56F   57                     push    edi
005DD570   8BD8                   mov     ebx, eax
005DD572   33C0                   xor     eax, eax
005DD574   55                     push    ebp
005DD575   6810D65D00             push    $005DD610

***** TRY
|
005DD57A   64FF30                 push    dword ptr fs:[eax]
005DD57D   648920                 mov     fs:[eax], esp

* Reference to control TFrmSelRelUnorcProg.lista_chk : TCheckListBox
|
005DD580   8B8310030000           mov     eax, [ebx+$0310]

* Reference to field TCheckListBox.OFFS_0218
|
005DD586   8B8018020000           mov     eax, [eax+$0218]
005DD58C   8B10                   mov     edx, [eax]
005DD58E   FF5214                 call    dword ptr [edx+$14]
005DD591   8BF0                   mov     esi, eax
005DD593   4E                     dec     esi
005DD594   85F6                   test    esi, esi
005DD596   7C62                   jl      005DD5FA
005DD598   46                     inc     esi
005DD599   C705082D610000000000   mov     dword ptr [$00612D08], $00000000
005DD5A3   8B15082D6100           mov     edx, [$00612D08]

* Reference to control TFrmSelRelUnorcProg.lista_chk : TCheckListBox
|
005DD5A9   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: CheckLst.Proc_004AE788
|
005DD5AF   E8D411EDFF             call    004AE788
005DD5B4   84C0                   test    al, al
005DD5B6   7439                   jz      005DD5F1
005DD5B8   A1082D6100             mov     eax, dword ptr [$00612D08]
005DD5BD   8D848320030000         lea     eax, [ebx+eax*4+$0320]
005DD5C4   50                     push    eax
005DD5C5   8D4DFC                 lea     ecx, [ebp-$04]

* Reference to control TFrmSelRelUnorcProg.lista_chk : TCheckListBox
|
005DD5C8   8B8310030000           mov     eax, [ebx+$0310]

* Reference to field TCheckListBox.OFFS_0218
|
005DD5CE   8B8018020000           mov     eax, [eax+$0218]
005DD5D4   8B15082D6100           mov     edx, [$00612D08]
005DD5DA   8B38                   mov     edi, [eax]
005DD5DC   FF570C                 call    dword ptr [edi+$0C]
005DD5DF   8B45FC                 mov     eax, [ebp-$04]
005DD5E2   B905000000             mov     ecx, $00000005
005DD5E7   BA01000000             mov     edx, $00000001

* Reference to: System.Proc_00404C74
|
005DD5EC   E88376E2FF             call    00404C74
005DD5F1   FF05082D6100           inc     dword ptr [$00612D08]
005DD5F7   4E                     dec     esi
005DD5F8   75A9                   jnz     005DD5A3
005DD5FA   33C0                   xor     eax, eax
005DD5FC   5A                     pop     edx
005DD5FD   59                     pop     ecx
005DD5FE   59                     pop     ecx
005DD5FF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[Y]√ç@'
|
005DD602   6817D65D00             push    $005DD617
005DD607   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00404764
|
005DD60A   E85571E2FF             call    00404764
005DD60F   C3                     ret


* Reference to: System.Proc_00404028
|
005DD610   E9136AE2FF             jmp     00404028
005DD615   EBF0                   jmp     005DD607

****** END
|
005DD617   5F                     pop     edi
005DD618   5E                     pop     esi
005DD619   5B                     pop     ebx
005DD61A   59                     pop     ecx
005DD61B   5D                     pop     ebp
005DD61C   C3                     ret

*)
end;

procedure TFrmSelRelUnorcProg.BitBtn2Click(Sender : TObject);
Var
  I : integer;
begin
    For i := 0 to lista_chk.Count - 1 do
        lista_chk.Checked[i] := True;
end;

procedure TFrmSelRelUnorcProg.BitBtn4Click(Sender : TObject);
begin
(*
005DD654   C3                     ret

*)
end;

procedure TFrmSelRelUnorcProg.BitBtn3Click(Sender : TObject);
Var
  I : integer;
begin
    For i := 0 to lista_chk.Count - 1 do
        lista_chk.Checked[i] := False;

end;

procedure TFrmSelRelUnorcProg.qyrPro(Sender : TObject);
begin
(*
005DD68C   C3                     ret

*)
end;

procedure TFrmSelRelUnorcProg._PROC_005DD1C1(Sender : TObject);
begin
(*
005DD1C1   6E                     outsb
005DD1C2   6F                     outsd
005DD1C3   7263                   jb      005DD228
005DD1C5   44                     inc     esp
005DD1C6   2020                   and     [eax], ah
005DD1C8   2020                   and     [eax], ah
005DD1CA   2020                   and     [eax], ah
005DD1CC   202C61                 and     [ecx], ch
005DD1CF   2E7072                 jo      005DD244
005DD1D2   6F                     outsd
005DD1D3   677261                 jb      005DD237
005DD1D6   6D                     insd
005DD1D7   61                     popa
005DD1D8   2C70                   sub     al, $70
005DD1DA   2E64657363             jnb     005DD242
005DD1DF   7269                   jb      005DD24A
005DD1E1   63616F                 arpl    [ecx+$6F], sp
005DD1E4   206173                 and     [ecx+$73], ah
005DD1E7   207072                 and     [eax+$72], dh
005DD1EA   6F                     outsd
005DD1EB   677261                 jb      005DD24F
005DD1EE   6D                     insd
005DD1EF   61                     popa
005DD1F0   44                     inc     esp
005DD1F1   2020                   and     [eax], ah
005DD1F3   2020                   and     [eax], ah
005DD1F5   2020                   and     [eax], ah
005DD1F7   2020                   and     [eax], ah
005DD1F9   2020                   and     [eax], ah
005DD1FB   2020                   and     [eax], ah
005DD1FD   2020                   and     [eax], ah
005DD1FF   2020                   and     [eax], ah
005DD201   2C76                   sub     al, $76
005DD203   61                     popa
005DD204   6C                     insb
005DD205   6F                     outsd
005DD206   7220                   jb      005DD228
005DD208   3D20636173             cmp     eax, $73616320
005DD20D   652020                 and     gs:[eax], ah
005DD210   7768                   jnbe    005DD27A
005DD212   656E                   outsb
005DD214   207375                 and     [ebx+$75], dh
005DD217   6D                     insd
005DD218   28612E                 sub     [ecx+$2E], ah
005DD21B   7661                   jbe     005DD27E
005DD21D   6C                     insb
005DD21E   6F                     outsd
005DD21F   7229                   jb      005DD24A
005DD221   3D30206F72             cmp     eax, $726F2030
005DD226   207375                 and     [ebx+$75], dh
005DD229   6D                     insd
005DD22A   28612E                 sub     [ecx+$2E], ah
005DD22D   7661                   jbe     005DD290
005DD22F   6C                     insb
005DD230   6F                     outsd
005DD231   7229                   jb      005DD25C
005DD233   2020                   and     [eax], ah
005DD235   6973206E756C6C         imul    esi, [ebx+$20], $6C6C756E
005DD23C   20746865               and     [eax+ebp*2+$65], dh
005DD240   6E                     outsb
005DD241   2030                   and     [eax], dh
005DD243   20656C                 and     [ebp+$6C], ah
005DD246   7365                   jnb     005DD2AD
005DD248   207375                 and     [ebx+$75], dh
005DD24B   6D                     insd
005DD24C   28612E                 sub     [ecx+$2E], ah
005DD24F   7661                   jbe     005DD2B2
005DD251   6C                     insb
005DD252   6F                     outsd
005DD253   7229                   jb      005DD27E
005DD255   20656E                 and     [ebp+$6E], ah
005DD258   642020                 and     fs:[eax], ah
005DD25B   2020                   and     [eax], ah
005DD25D   2020                   and     [eax], ah
005DD25F   2020                   and     [eax], ah
005DD261   2020                   and     [eax], ah
005DD263   2020                   and     [eax], ah
005DD265   2020                   and     [eax], ah
005DD267   2020                   and     [eax], ah
005DD269   204652                 and     [esi+$52], al
005DD26C   4F                     dec     edi
005DD26D   4D                     dec     ebp
005DD26E   20414E                 and     [ecx+$4E], al
005DD271   4F                     dec     edi
005DD272   53                     push    ebx
005DD273   45                     inc     ebp
005DD274   47                     inc     edi
005DD275   55                     push    ebp
005DD276   49                     dec     ecx
005DD277   4E                     dec     esi
005DD278   54                     push    esp
005DD279   45                     inc     ebp
005DD27A   206120                 and     [ecx+$20], ah
005DD27D   2020                   and     [eax], ah
005DD27F   2020                   and     [eax], ah
005DD281   2020                   and     [eax], ah
005DD283   2020                   and     [eax], ah
005DD285   2020                   and     [eax], ah
005DD287   2020                   and     [eax], ah
005DD289   2020                   and     [eax], ah
005DD28B   2020                   and     [eax], ah
005DD28D   2020                   and     [eax], ah
005DD28F   2020                   and     [eax], ah
005DD291   2020                   and     [eax], ah
005DD293   2020                   and     [eax], ah
005DD295   2020                   and     [eax], ah
005DD297   2020                   and     [eax], ah
005DD299   2020                   and     [eax], ah
005DD29B   2020                   and     [eax], ah
005DD29D   4C                     dec     esp
005DD29E   45                     inc     ebp
005DD29F   46                     inc     esi
005DD2A0   54                     push    esp
005DD2A1   204A4F                 and     [edx+$4F], cl
005DD2A4   49                     dec     ecx
005DD2A5   4E                     dec     esi
005DD2A6   20554E                 and     [ebp+$4E], dl
005DD2A9   4F                     dec     edi
005DD2AA   52                     push    edx
005DD2AB   43                     inc     ebx
005DD2AC   207520                 and     [ebp+$20], dh
005DD2AF   6F                     outsd
005DD2B0   6E                     outsb
005DD2B1   20752E                 and     [ebp+$2E], dh
005DD2B4   636F64                 arpl    [edi+$64], bp
005DD2B7   69676F203D2061         imul    esp, [edi+$6F], $61203D20
005DD2BE   2E756E                 jnz     005DD32F
005DD2C1   6F                     outsd
005DD2C2   7263                   jb      005DD327
005DD2C4   2020                   and     [eax], ah
005DD2C6   2020                   and     [eax], ah
005DD2C8   2020                   and     [eax], ah
005DD2CA   2020                   and     [eax], ah
005DD2CC   2020                   and     [eax], ah
005DD2CE   2020                   and     [eax], ah
005DD2D0   204C4546               and     [ebp+eax*2+$46], cl
005DD2D4   54                     push    esp
005DD2D5   204A4F                 and     [edx+$4F], cl
005DD2D8   49                     dec     ecx
005DD2D9   4E                     dec     esi
005DD2DA   205052                 and     [eax+$52], dl
005DD2DD   4F                     dec     edi
005DD2DE   47                     inc     edi
005DD2DF   52                     push    edx
005DD2E0   41                     inc     ecx
005DD2E1   4D                     dec     ebp
005DD2E2   41                     inc     ecx
005DD2E3   207020                 and     [eax+$20], dh
005DD2E6   6F                     outsd
005DD2E7   6E                     outsb
005DD2E8   20702E                 and     [eax+$2E], dh
005DD2EB   636F64                 arpl    [edi+$64], bp
005DD2EE   69676F203D2061         imul    esp, [edi+$6F], $61203D20
005DD2F5   2E7072                 jo      005DD36A
005DD2F8   6F                     outsd
005DD2F9   677261                 jb      005DD35D
005DD2FC   6D                     insd
005DD2FD   61                     popa
005DD2FE   2020                   and     [eax], ah
005DD300   2020                   and     [eax], ah
005DD302   2020                   and     [eax], ah
005DD304   204C4546               and     [ebp+eax*2+$46], cl
005DD308   54                     push    esp
005DD309   204A4F                 and     [edx+$4F], cl
005DD30C   49                     dec     ecx
005DD30D   4E                     dec     esi
005DD30E   204143                 and     [ecx+$43], al
005DD311   41                     inc     ecx
005DD312   4F                     dec     edi
005DD313   206163                 and     [ecx+$63], ah
005DD316   206F6E                 and     [edi+$6E], ch
005DD319   206163                 and     [ecx+$63], ah
005DD31C   2E636F64               arpl    cs:[edi+$64], bp
005DD320   69676F203D2061         imul    esp, [edi+$6F], $61203D20
005DD327   2E61                   popa
005DD329   63616F                 arpl    [ecx+$6F], sp
005DD32C   2020                   and     [eax], ah
005DD32E   2020                   and     [eax], ah
005DD330   2020                   and     [eax], ah
005DD332   2020                   and     [eax], ah
005DD334   2020                   and     [eax], ah
005DD336   2020                   and     [eax], ah
005DD338   207768                 and     [edi+$68], dh
005DD33B   657265                 jb      005DD3A3
005DD33E   2031                   and     [ecx], dh
005DD340   203D20312020           and     [$20203120], bh
005DD346   2020                   and     [eax], ah
005DD348   2020                   and     [eax], ah
005DD34A   2020                   and     [eax], ah
005DD34C   2020                   and     [eax], ah
005DD34E   2020                   and     [eax], ah
005DD350   2020                   and     [eax], ah
005DD352   2020                   and     [eax], ah
005DD354   2020                   and     [eax], ah
005DD356   2020                   and     [eax], ah
005DD358   2020                   and     [eax], ah
005DD35A   2020                   and     [eax], ah
005DD35C   2020                   and     [eax], ah
005DD35E   2020                   and     [eax], ah
005DD360   2020                   and     [eax], ah
005DD362   2020                   and     [eax], ah
005DD364   2020                   and     [eax], ah
005DD366   2020                   and     [eax], ah
005DD368   2020                   and     [eax], ah
005DD36A   2020                   and     [eax], ah
005DD36C   0000                   add     [eax], al

*)
end;




procedure TFrmSelRelUnorcProg.ListaOrgaos;
begin
   QRYUnorc.Close;
   QRYUnorc.open;
   QRYUnorc.First;

   while not QRYUnorc.Eof do
   Begin
      lista_chk.Items.Add(QRYUnorccodigo.Value +' - '+QRYUnorcdescricao.Value);
      QRYUnorc.Next;
   End;
end;

procedure TFrmSelRelUnorcProg.Pesquisa(Parametro: String);
begin
   QRYUnorc.Close;
   qryUnorc.SQL.Clear;
   qryUnorc.SQL.Add(Lista_SQL);
   qryUnorc.SQL.Add('Where U.Codigo = :Param');
   qryUnorc.Parameters.ParamByName('Param').Value := Parametro;
   qryUnorc.ExecSQL;
   qryUnorc.Open;
end;



end.
